var CHENZIHAHA_DATA = [
  {
    "title": "Coastal moments",
    "date": "2026-05-03",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 166,
    "comments": 15,
    "saves": 15,
    "fans": null,
    "shares": 1,
    "save_rate": 0.076,
    "quality_index": 1.24,
    "score": 30
  },
  {
    "title": "Neutral Vibe",
    "date": "2026-05-02",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 175,
    "comments": 14,
    "saves": 28,
    "fans": null,
    "shares": 2,
    "save_rate": 0.128,
    "quality_index": 1.22,
    "score": 34
  },
  {
    "title": "Black & White",
    "date": "2026-05-01",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 304,
    "comments": 28,
    "saves": 69,
    "fans": null,
    "shares": 6,
    "save_rate": 0.17,
    "quality_index": 1.25,
    "score": 40
  },
  {
    "title": "Subtle Shine",
    "date": "2026-04-30",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 282,
    "comments": 19,
    "saves": 70,
    "fans": null,
    "shares": 3,
    "save_rate": 0.187,
    "quality_index": 1.18,
    "score": 38
  },
  {
    "title": "Soft White Days",
    "date": "2026-04-29",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 532,
    "comments": 25,
    "saves": 93,
    "fans": null,
    "shares": 17,
    "save_rate": 0.139,
    "quality_index": 1.19,
    "score": 34
  },
  {
    "title": "Urban Diary",
    "date": "2026-04-28",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 382,
    "comments": 25,
    "saves": 52,
    "fans": null,
    "shares": 14,
    "save_rate": 0.11,
    "quality_index": 1.25,
    "score": 34
  },
  {
    "title": "Lazy & Loose",
    "date": "2026-04-27",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 473,
    "comments": 34,
    "saves": 75,
    "fans": null,
    "shares": 13,
    "save_rate": 0.126,
    "quality_index": 1.24,
    "score": 35
  },
  {
    "title": "Aesthetic in Black",
    "date": "2026-04-26",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 527,
    "comments": 21,
    "saves": 68,
    "fans": null,
    "shares": 31,
    "save_rate": 0.105,
    "quality_index": 1.24,
    "score": 33
  },
  {
    "title": "Minimal Style",
    "date": "2026-04-25",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 403,
    "comments": 26,
    "saves": 55,
    "fans": null,
    "shares": 13,
    "save_rate": 0.111,
    "quality_index": 1.24,
    "score": 33
  },
  {
    "title": "Day to Night Look",
    "date": "2026-04-23",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 648,
    "comments": 32,
    "saves": 120,
    "fans": null,
    "shares": 31,
    "save_rate": 0.14400000000000002,
    "quality_index": 1.23,
    "score": 36
  },
  {
    "title": "Tailored Noir",
    "date": "2026-04-23",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 301,
    "comments": 30,
    "saves": 34,
    "fans": null,
    "shares": 6,
    "save_rate": 0.092,
    "quality_index": 1.29,
    "score": 35
  },
  {
    "title": "Urban Elegance",
    "date": "2026-04-22",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 269,
    "comments": 29,
    "saves": 33,
    "fans": null,
    "shares": 4,
    "save_rate": 0.099,
    "quality_index": 1.3,
    "score": 35
  },
  {
    "title": "Techwear Aesthetic",
    "date": "2026-04-21",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 503,
    "comments": 29,
    "saves": 66,
    "fans": null,
    "shares": 17,
    "save_rate": 0.107,
    "quality_index": 1.22,
    "score": 32
  },
  {
    "title": "Street Romance",
    "date": "2026-04-20",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 297,
    "comments": 25,
    "saves": 32,
    "fans": null,
    "shares": 3,
    "save_rate": 0.09,
    "quality_index": 1.24,
    "score": 31
  },
  {
    "title": "Urban Floral",
    "date": "2026-04-19",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 711,
    "comments": 25,
    "saves": 100,
    "fans": null,
    "shares": 38,
    "save_rate": 0.114,
    "quality_index": 1.22,
    "score": 33
  },
  {
    "title": "Valley Vibe",
    "date": "2026-04-17",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 389,
    "comments": 20,
    "saves": 51,
    "fans": null,
    "shares": 5,
    "save_rate": 0.11,
    "quality_index": 1.16,
    "score": 29
  },
  {
    "title": "Quiet Luxury",
    "date": "2026-04-11",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 873,
    "comments": 41,
    "saves": 134,
    "fans": null,
    "shares": 47,
    "save_rate": 0.122,
    "quality_index": 1.24,
    "score": 35
  },
  {
    "title": "Minimal Chic",
    "date": "2026-04-10",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 443,
    "comments": 52,
    "saves": 62,
    "fans": null,
    "shares": 6,
    "save_rate": 0.11,
    "quality_index": 1.31,
    "score": 37
  },
  {
    "title": "Window Glow, Slow Read",
    "date": "2026-04-09",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 411,
    "comments": 22,
    "saves": 52,
    "fans": null,
    "shares": 9,
    "save_rate": 0.105,
    "quality_index": 1.19,
    "score": 30
  },
  {
    "title": "Blossom in Silhouette",
    "date": "2026-04-08",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 546,
    "comments": 43,
    "saves": 47,
    "fans": null,
    "shares": 15,
    "save_rate": 0.07200000000000001,
    "quality_index": 1.27,
    "score": 31
  }
];

var CHENZIHAHA_META = {
  "nickname": "陈紫haha",
  "xhs_id": 748631317,
  "bio": "📂𝟙𝟠𝟙𝟛𝟘𝟘𝟛𝟜𝟠𝟙@𝕢𝕢.𝕔𝕠𝕞",
  "location": "浙江",
  "followers": 172195,
  "following": 107,
  "notes_count": 1340,
  "total_likes": 981806,
  "total_saves": 161707,
  "total_likes_and_saves": 1143513,
  "total_engagement": 10727,
  "avg_save_rate": 0.11599999999999999,
  "avg_quality_index": 1.23,
  "avg_comment_ratio": 0.055999999999999994,
  "avg_score": 33,
  "analysis": "「陈紫haha」账号的爆款笔记集中在时尚穿搭领域，如「Quiet Luxury」「Day to Night Look」等，均以高收藏率（12.2%-14.4%）和稳定的互动质量指数（1.19-1.27）为特征，表明内容兼具审美价值与实用性，符合小红书用户收藏分享偏好。互动结构以收藏型为主（平均11.6%），辅以评论型（平均5.6%），分享型互动相对较弱（平均4.2%）。建议：1. 强化视觉呈现，提升内容美感以进一步提高收藏率；2. 优化评论区互动，如增加引导性问题，提升评论转化率至8%以上。",
  "profile_tags": {
    "content_theme": {
      "primary_vertical": "时尚穿搭",
      "sub_direction": "穿搭分享"
    },
    "content_style": {
      "audience_level": "小白向",
      "sentence_pattern": "清单型",
      "tone": "轻松分享"
    },
    "seeding_traits": {
      "seeding_tendency": "强种草",
      "suitable_ad_type": "消费品"
    },
    "engagement_traits": {
      "fan_activity": "中活跃",
      "content_burst": "稳定型",
      "seeding_efficiency": "均衡型"
    },
    "account_health": {
      "update_freq": "高频",
      "content_verticality": "高垂直",
      "engagement_authenticity": "正常"
    },
    "collab_fit": {
      "recommended_scenario": "生活植入",
      "brand_tone_match": "年轻潮流品牌"
    },
    "follower_tier": "腰部达人",
    "content_format": "图文为主",
    "tagged_at": "2026-05-03"
  }
};
