var CHENZIHAHA_DATA = [
  {
    "title": "Timeless vibe",
    "date": "2026-05-17",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 259,
    "comments": 15,
    "saves": 39,
    "fans": null,
    "shares": 11,
    "save_rate": 0.12,
    "quality_index": 1.24,
    "score": 35
  },
  {
    "title": "𝓡𝓮𝓽𝓾𝓻𝓷 𝓽𝓸 𝓯𝓻𝓮𝓷𝓬𝓮",
    "date": "2026-05-16",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 214,
    "comments": 27,
    "saves": 25,
    "fans": null,
    "shares": 5,
    "save_rate": 0.092,
    "quality_index": 1.35,
    "score": 38
  },
  {
    "title": "Casual Chic Mood",
    "date": "2026-05-16",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 219,
    "comments": 19,
    "saves": 30,
    "fans": null,
    "shares": 4,
    "save_rate": 0.11,
    "quality_index": 1.25,
    "score": 34
  },
  {
    "title": "Summer Whispers",
    "date": "2026-05-15",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 314,
    "comments": 17,
    "saves": 71,
    "fans": null,
    "shares": 7,
    "save_rate": 0.174,
    "quality_index": 1.18,
    "score": 36
  },
  {
    "title": "Sleek & Simple",
    "date": "2026-05-14",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1075,
    "comments": 26,
    "saves": 162,
    "fans": null,
    "shares": 86,
    "save_rate": 0.12,
    "quality_index": 1.25,
    "score": 35
  },
  {
    "title": "Blue Print Summer",
    "date": "2026-05-13",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 436,
    "comments": 28,
    "saves": 59,
    "fans": null,
    "shares": 17,
    "save_rate": 0.109,
    "quality_index": 1.25,
    "score": 34
  },
  {
    "title": "Gentle Glow",
    "date": "2026-05-12",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 340,
    "comments": 24,
    "saves": 47,
    "fans": null,
    "shares": 14,
    "save_rate": 0.111,
    "quality_index": 1.27,
    "score": 35
  },
  {
    "title": "Classic minimal look",
    "date": "2026-05-11",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 334,
    "comments": 25,
    "saves": 47,
    "fans": null,
    "shares": 8,
    "save_rate": 0.114,
    "quality_index": 1.24,
    "score": 34
  },
  {
    "title": "Grey Tone",
    "date": "2026-05-10",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 749,
    "comments": 29,
    "saves": 110,
    "fans": null,
    "shares": 46,
    "save_rate": 0.11800000000000001,
    "quality_index": 1.24,
    "score": 34
  },
  {
    "title": "It’s my birthday",
    "date": "2026-05-09",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 344,
    "comments": 69,
    "saves": 33,
    "fans": null,
    "shares": 6,
    "save_rate": 0.073,
    "quality_index": 1.5,
    "score": 44
  },
  {
    "title": "Quiet Elegance",
    "date": "2026-05-08",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 281,
    "comments": 21,
    "saves": 44,
    "fans": null,
    "shares": 6,
    "save_rate": 0.125,
    "quality_index": 1.23,
    "score": 35
  },
  {
    "title": "Soft Grey Vibe",
    "date": "2026-05-07",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 283,
    "comments": 17,
    "saves": 37,
    "fans": null,
    "shares": 5,
    "save_rate": 0.10800000000000001,
    "quality_index": 1.19,
    "score": 31
  },
  {
    "title": "Floral Muted",
    "date": "2026-05-06",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 318,
    "comments": 58,
    "saves": 72,
    "fans": null,
    "shares": 6,
    "save_rate": 0.159,
    "quality_index": 1.42,
    "score": 48
  },
  {
    "title": "All Black Date",
    "date": "2026-05-05",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 321,
    "comments": 28,
    "saves": 44,
    "fans": null,
    "shares": 8,
    "save_rate": 0.11,
    "quality_index": 1.27,
    "score": 35
  },
  {
    "title": "Coastal moments",
    "date": "2026-05-03",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 351,
    "comments": 24,
    "saves": 29,
    "fans": null,
    "shares": 5,
    "save_rate": 0.071,
    "quality_index": 1.21,
    "score": 28
  },
  {
    "title": "Neutral Vibe",
    "date": "2026-05-02",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 217,
    "comments": 14,
    "saves": 36,
    "fans": null,
    "shares": 2,
    "save_rate": 0.134,
    "quality_index": 1.18,
    "score": 33
  },
  {
    "title": "Black & White",
    "date": "2026-05-01",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 356,
    "comments": 30,
    "saves": 76,
    "fans": null,
    "shares": 8,
    "save_rate": 0.162,
    "quality_index": 1.24,
    "score": 39
  },
  {
    "title": "Subtle Shine",
    "date": "2026-04-30",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 301,
    "comments": 18,
    "saves": 73,
    "fans": null,
    "shares": 3,
    "save_rate": 0.185,
    "quality_index": 1.16,
    "score": 37
  },
  {
    "title": "Soft White Days",
    "date": "2026-04-29",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 588,
    "comments": 24,
    "saves": 100,
    "fans": null,
    "shares": 19,
    "save_rate": 0.13699999999999998,
    "quality_index": 1.18,
    "score": 33
  },
  {
    "title": "Urban Diary",
    "date": "2026-04-28",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 400,
    "comments": 28,
    "saves": 57,
    "fans": null,
    "shares": 20,
    "save_rate": 0.113,
    "quality_index": 1.29,
    "score": 36
  }
];

var CHENZIHAHA_META = {
  "nickname": "陈紫haha",
  "xhs_id": 748631317,
  "bio": "📂𝟙𝟠𝟙𝟛𝟘𝟘𝟛𝟜𝟠𝟙@𝕢𝕢.𝕔𝕠𝕞",
  "location": "Shanghai",
  "followers": 172042,
  "following": 107,
  "notes_count": 1354,
  "total_likes": 987783,
  "total_saves": 162541,
  "total_likes_and_saves": 1150324,
  "total_engagement": 9718,
  "avg_save_rate": 0.122,
  "avg_quality_index": 1.26,
  "avg_comment_ratio": 0.062,
  "avg_score": 35,
  "analysis": "「陈紫haha」账号的爆款笔记均以视觉风格（如「Sleek & Simple」「Grey Tone」）和生活方式记录（如「Urban Diary」）为主，收藏率与互动质量指数表现稳定，说明内容兼具实用性和审美价值。互动结构上，收藏率（12.2%）显著高于评论率（6.2%），呈现典型的收藏型互动特点，用户更倾向于保存内容以备后续参考。建议：\n1. 持续深化视觉风格类内容，如增加「色彩搭配指南」等教程笔记，提升收藏转化；\n2. 通过发起「笔记使用打卡」等互动话题，平衡收藏与评论互动，增强用户参与感。",
  "profile_tags": {
    "content_theme": {
      "primary_vertical": "时尚穿搭",
      "sub_direction": "穿搭分享"
    },
    "content_style": {
      "audience_level": "小白向",
      "sentence_pattern": "清单型",
      "tone": "轻松分享"
    },
    "seeding_traits": {
      "seeding_tendency": "强种草",
      "suitable_ad_type": "消费品"
    },
    "engagement_traits": {
      "fan_activity": "中活跃",
      "content_burst": "稳定型",
      "seeding_efficiency": "均衡型"
    },
    "account_health": {
      "update_freq": "高频",
      "content_verticality": "高垂直",
      "engagement_authenticity": "正常"
    },
    "collab_fit": {
      "recommended_scenario": "生活植入",
      "brand_tone_match": "生活方式品牌"
    },
    "follower_tier": "腰部达人",
    "content_format": "图文为主",
    "tagged_at": "2026-05-17"
  }
};
