var CHENZIHAHA_DATA = [
  {
    "title": "Urban Floral",
    "date": "2026-04-19",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 367,
    "comments": 20,
    "saves": 51,
    "fans": null,
    "shares": 15,
    "save_rate": 0.113,
    "quality_index": 1.23,
    "score": 33
  },
  {
    "title": "Valley Vibe",
    "date": "2026-04-17",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 328,
    "comments": 19,
    "saves": 42,
    "fans": null,
    "shares": 4,
    "save_rate": 0.107,
    "quality_index": 1.18,
    "score": 30
  },
  {
    "title": "Quiet Luxury",
    "date": "2026-04-11",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 833,
    "comments": 42,
    "saves": 116,
    "fans": null,
    "shares": 45,
    "save_rate": 0.11199999999999999,
    "quality_index": 1.25,
    "score": 34
  },
  {
    "title": "Minimal Chic",
    "date": "2026-04-10",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 431,
    "comments": 53,
    "saves": 61,
    "fans": null,
    "shares": 6,
    "save_rate": 0.111,
    "quality_index": 1.32,
    "score": 38
  },
  {
    "title": "Window Glow, Slow Read",
    "date": "2026-04-09",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 406,
    "comments": 22,
    "saves": 48,
    "fans": null,
    "shares": 6,
    "save_rate": 0.1,
    "quality_index": 1.17,
    "score": 29
  },
  {
    "title": "Blossom in Silhouette",
    "date": "2026-04-08",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 536,
    "comments": 43,
    "saves": 45,
    "fans": null,
    "shares": 15,
    "save_rate": 0.07,
    "quality_index": 1.27,
    "score": 31
  },
  {
    "title": "Black Wardrobe Diaries",
    "date": "2026-04-07",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 960,
    "comments": 38,
    "saves": 181,
    "fans": null,
    "shares": 88,
    "save_rate": 0.14300000000000002,
    "quality_index": 1.3,
    "score": 40
  },
  {
    "title": "Slow Sunday",
    "date": "2026-04-05",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 899,
    "comments": 40,
    "saves": 113,
    "fans": null,
    "shares": 56,
    "save_rate": 0.102,
    "quality_index": 1.26,
    "score": 34
  },
  {
    "title": "Clean Lines",
    "date": "2026-04-03",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 440,
    "comments": 27,
    "saves": 52,
    "fans": null,
    "shares": 15,
    "save_rate": 0.09699999999999999,
    "quality_index": 1.24,
    "score": 32
  },
  {
    "title": "soft sage",
    "date": "2026-04-03",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 521,
    "comments": 29,
    "saves": 81,
    "fans": null,
    "shares": 33,
    "save_rate": 0.122,
    "quality_index": 1.28,
    "score": 37
  },
  {
    "title": "Calm & Chic",
    "date": "2026-04-01",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 388,
    "comments": 34,
    "saves": 50,
    "fans": null,
    "shares": 9,
    "save_rate": 0.10400000000000001,
    "quality_index": 1.27,
    "score": 34
  },
  {
    "title": "Vintage Noir",
    "date": "2026-04-01",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1645,
    "comments": 68,
    "saves": 225,
    "fans": null,
    "shares": 96,
    "save_rate": 0.111,
    "quality_index": 1.24,
    "score": 34
  },
  {
    "title": "Curated Looks",
    "date": "2026-03-31",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 703,
    "comments": 27,
    "saves": 254,
    "fans": null,
    "shares": 33,
    "save_rate": 0.25,
    "quality_index": 1.18,
    "score": 44
  },
  {
    "title": "Eastern Runway",
    "date": "2026-03-29",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 304,
    "comments": 42,
    "saves": 33,
    "fans": null,
    "shares": 7,
    "save_rate": 0.085,
    "quality_index": 1.38,
    "score": 39
  },
  {
    "title": "Red Velvet Moment",
    "date": "2026-03-29",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 374,
    "comments": 44,
    "saves": 45,
    "fans": null,
    "shares": 7,
    "save_rate": 0.096,
    "quality_index": 1.33,
    "score": 37
  },
  {
    "title": "Dymonlatry Fall Edit",
    "date": "2026-03-28",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 310,
    "comments": 31,
    "saves": 47,
    "fans": null,
    "shares": 9,
    "save_rate": 0.11800000000000001,
    "quality_index": 1.3,
    "score": 38
  },
  {
    "title": "Timeless Elegance",
    "date": "2026-03-27",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 314,
    "comments": 28,
    "saves": 32,
    "fans": null,
    "shares": 0,
    "save_rate": 0.086,
    "quality_index": 1.22,
    "score": 30
  },
  {
    "title": "Golden Glow",
    "date": "2026-03-26",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1156,
    "comments": 37,
    "saves": 243,
    "fans": null,
    "shares": 65,
    "save_rate": 0.162,
    "quality_index": 1.2,
    "score": 37
  },
  {
    "title": "Mint Whisper",
    "date": "2026-03-25",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 360,
    "comments": 41,
    "saves": 65,
    "fans": null,
    "shares": 8,
    "save_rate": 0.13699999999999998,
    "quality_index": 1.31,
    "score": 40
  },
  {
    "title": "穿搭博主 衣服盲盒",
    "date": "2026-03-24",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 412,
    "comments": 135,
    "saves": 137,
    "fans": null,
    "shares": 27,
    "save_rate": 0.193,
    "quality_index": 1.68,
    "score": 61
  }
];

var CHENZIHAHA_META = {
  "nickname": "陈紫haha",
  "xhs_id": 748631317,
  "bio": "📂𝟙𝟠𝟙𝟛𝟘𝟘𝟛𝟜𝟠𝟙@𝕢𝕢.𝕔𝕠𝕞",
  "location": "上海",
  "followers": 172471,
  "following": 104,
  "notes_count": 1325,
  "total_likes": 976031,
  "total_saves": 160841,
  "total_likes_and_saves": 1136872,
  "total_engagement": 14972,
  "avg_save_rate": 0.121,
  "avg_quality_index": 1.28,
  "avg_comment_ratio": 0.064,
  "avg_score": 36,
  "analysis": "「陈紫haha」账号的爆款笔记集中在穿搭、氛围感等视觉化内容，如「Vintage Noir」「Golden Glow」等，收藏率与综合评分均表现优异，证明高质量图片+氛围营造是关键。互动结构以收藏型为主（TOP5笔记收藏率均超10%），辅以评论型互动（平均评论/互动比6.4%），分享型互动相对较弱（平均分享量仅51）。建议：1. 强化视觉叙事，保持穿搭笔记的细节质感与故事性，提升收藏率；2. 适当增加互动引导，如提问式标题或评论区话题，提升评论/互动比，平衡各互动维度发展。"
};
