var LIANGKEBAN_DATA = [
  {
    "title": "我把Karpathy个人知识管理方法做成了skill",
    "date": "2026-04-06",
    "type": "图文",
    "impressions": 3760,
    "views": 722,
    "ctr": 0.172,
    "likes": 33,
    "comments": 2,
    "saves": 107,
    "fans": 2,
    "shares": 19,
    "save_rate": 0.665,
    "quality_index": 1.39,
    "score": 9
  },
  {
    "title": "🚀Gemma 4 的 8 个版本怎么选？一文看懂！",
    "date": "2026-04-03",
    "type": "图文",
    "impressions": 4711,
    "views": 750,
    "ctr": 0.153,
    "likes": 16,
    "comments": 0,
    "saves": 27,
    "fans": 1,
    "shares": 4,
    "save_rate": 0.574,
    "quality_index": 1.26,
    "score": 7
  },
  {
    "title": "AI 重塑组织：Block 的\"智能体公司\"实验",
    "date": "2026-04-01",
    "type": "图文",
    "impressions": 1386,
    "views": 158,
    "ctr": 0.106,
    "likes": 6,
    "comments": 2,
    "saves": 10,
    "fans": 1,
    "shares": 0,
    "save_rate": 0.556,
    "quality_index": 1.33,
    "score": 10
  },
  {
    "title": "axios被投毒！建议所有养🦞的朋友立即自检",
    "date": "2026-03-31",
    "type": "图文",
    "impressions": 1635,
    "views": 217,
    "ctr": 0.133,
    "likes": 5,
    "comments": 0,
    "saves": 2,
    "fans": 0,
    "shares": 3,
    "save_rate": 0.2,
    "quality_index": 1.9,
    "score": 5
  },
  {
    "title": "造好 Harness，Agent 会完成剩下的",
    "date": "2026-03-27",
    "type": "图文",
    "impressions": 159,
    "views": 6,
    "ctr": 0.038,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "苹果秘密协议曝光！把Gemini放到iPhone 里？",
    "date": "2026-03-27",
    "type": "图文",
    "impressions": 697,
    "views": 35,
    "ctr": 0.052,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "林俊暘离开阿里首度发声：AI 下一个方向是它",
    "date": "2026-03-26",
    "type": "图文",
    "impressions": 338,
    "views": 13,
    "ctr": 0.036,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "🍌banana pro 一次生成多张黑白票据图技巧",
    "date": "2026-03-26",
    "type": "图文",
    "impressions": 747,
    "views": 16,
    "ctr": 0.019,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.0,
    "quality_index": 2.0,
    "score": 1
  },
  {
    "title": "🦞微信里也可以实现养虾自由啦！含详细教程",
    "date": "2026-03-22",
    "type": "图文",
    "impressions": 455,
    "views": 61,
    "ctr": 0.138,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "🔥 国产AI反向输出美国科技圈",
    "date": "2026-03-21",
    "type": "图文",
    "impressions": 442,
    "views": 28,
    "ctr": 0.05,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "Skill实战手册：装了100个不如用好1个",
    "date": "2026-03-20",
    "type": "图文",
    "impressions": 596,
    "views": 52,
    "ctr": 0.082,
    "likes": 1,
    "comments": 2,
    "saves": 2,
    "fans": 1,
    "shares": 0,
    "save_rate": 0.4,
    "quality_index": 2.2,
    "score": 11
  },
  {
    "title": "🚀 英伟达GTC2026完全看懂这篇就够了",
    "date": "2026-03-17",
    "type": "图文",
    "impressions": 818,
    "views": 102,
    "ctr": 0.116,
    "likes": 1,
    "comments": 0,
    "saves": 2,
    "fans": 1,
    "shares": 4,
    "save_rate": 0.286,
    "quality_index": 2.71,
    "score": 7
  },
  {
    "title": "🤖 AI 团队时代来临！147个AI特工任你调配",
    "date": "2026-03-15",
    "type": "图文",
    "impressions": 84,
    "views": 1,
    "ctr": 0.036,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "想知道龙虾有多了解你，问这三个问题就够了",
    "date": "2026-03-13",
    "type": "图文",
    "impressions": 479,
    "views": 39,
    "ctr": 0.088,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 1,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "🚀AI Agent架构：PI与OpenClaw解析",
    "date": "2026-03-12",
    "type": "图文",
    "impressions": 501,
    "views": 30,
    "ctr": 0.062,
    "likes": 2,
    "comments": 0,
    "saves": 1,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.333,
    "quality_index": 1.0,
    "score": 6
  },
  {
    "title": "Google 发布一个王炸模型，直接颠覆RAG！🔥",
    "date": "2026-03-11",
    "type": "图文",
    "impressions": 943,
    "views": 72,
    "ctr": 0.075,
    "likes": 2,
    "comments": 0,
    "saves": 3,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.5,
    "quality_index": 1.5,
    "score": 8
  },
  {
    "title": "🦞别再把龙虾当微信用了",
    "date": "2026-03-11",
    "type": "图文",
    "impressions": 437,
    "views": 25,
    "ctr": 0.057,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "4万个AI Skills，95%都是垃圾？",
    "date": "2026-03-10",
    "type": "图文",
    "impressions": 782,
    "views": 45,
    "ctr": 0.058,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.0,
    "quality_index": 2.0,
    "score": 1
  },
  {
    "title": "🔥 你的AI员工来了！",
    "date": "2026-03-07",
    "type": "图文",
    "impressions": 506,
    "views": 25,
    "ctr": 0.05,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.0,
    "quality_index": 2.0,
    "score": 1
  },
  {
    "title": "📝 央企成为AI规模化应用主力军",
    "date": "2026-03-06",
    "type": "图文",
    "impressions": 851,
    "views": 45,
    "ctr": 0.054,
    "likes": 1,
    "comments": 0,
    "saves": 2,
    "fans": 0,
    "shares": 2,
    "save_rate": 0.4,
    "quality_index": 2.2,
    "score": 8
  },
  {
    "title": "OpenClaw：开源新王！4个月速通25万Star奇迹",
    "date": "2026-03-03",
    "type": "图文",
    "impressions": 741,
    "views": 38,
    "ctr": 0.053,
    "likes": 2,
    "comments": 0,
    "saves": 1,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.333,
    "quality_index": 1.0,
    "score": 6
  },
  {
    "title": "养龙虾一个月，这些大实话说给你们听",
    "date": "2026-03-03",
    "type": "图文",
    "impressions": 68605,
    "views": 12008,
    "ctr": 0.181,
    "likes": 131,
    "comments": 2,
    "saves": 123,
    "fans": 10,
    "shares": 61,
    "save_rate": 0.388,
    "quality_index": 1.6,
    "score": 9
  },
  {
    "title": "人生中第一个动态红包封面送给你",
    "date": "2026-02-09",
    "type": "图文",
    "impressions": 387,
    "views": 11,
    "ctr": 0.028,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "OpenClaw 架构设计解密",
    "date": "2026-02-08",
    "type": "图文",
    "impressions": 1645,
    "views": 280,
    "ctr": 0.174,
    "likes": 4,
    "comments": 0,
    "saves": 4,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.5,
    "quality_index": 1.0,
    "score": 7
  },
  {
    "title": "AI 的灵魂文档究竟是什么",
    "date": "2026-02-07",
    "type": "图文",
    "impressions": 393,
    "views": 24,
    "ctr": 0.053,
    "likes": 0,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "OpenClaw一键解决90+顶尖技术博客智能筛选",
    "date": "2026-02-04",
    "type": "图文",
    "impressions": 1488,
    "views": 118,
    "ctr": 0.08,
    "likes": 5,
    "comments": 0,
    "saves": 7,
    "fans": 0,
    "shares": 2,
    "save_rate": 0.5,
    "quality_index": 1.43,
    "score": 7
  },
  {
    "title": "Claude Code 创始团队的10 条实用技巧",
    "date": "2026-02-02",
    "type": "图文",
    "impressions": 8522,
    "views": 959,
    "ctr": 0.112,
    "likes": 37,
    "comments": 3,
    "saves": 82,
    "fans": 5,
    "shares": 16,
    "save_rate": 0.594,
    "quality_index": 1.41,
    "score": 10
  },
  {
    "title": "OpenClaw记忆系统揭秘：告别“金鱼脑”",
    "date": "2026-02-02",
    "type": "图文",
    "impressions": 2129,
    "views": 199,
    "ctr": 0.095,
    "likes": 2,
    "comments": 0,
    "saves": 1,
    "fans": 0,
    "shares": 2,
    "save_rate": 0.2,
    "quality_index": 2.2,
    "score": 5
  },
  {
    "title": "谷歌AI新突破：让手机秒懂你的“小心思”🧠！",
    "date": "2026-01-26",
    "type": "图文",
    "impressions": 900,
    "views": 59,
    "ctr": 0.067,
    "likes": 2,
    "comments": 2,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 2.5,
    "score": 4
  },
  {
    "title": "2030年AGI可能性50%，白领工作可能还剩5年",
    "date": "2026-01-25",
    "type": "图文",
    "impressions": 443,
    "views": 30,
    "ctr": 0.07,
    "likes": 1,
    "comments": 0,
    "saves": 1,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.5,
    "quality_index": 1.0,
    "score": 7
  },
  {
    "title": "Anthropic公开了Claude的核心价值观",
    "date": "2026-01-23",
    "type": "图文",
    "impressions": 959,
    "views": 92,
    "ctr": 0.096,
    "likes": 2,
    "comments": 0,
    "saves": 2,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.5,
    "quality_index": 1.0,
    "score": 7
  },
  {
    "title": "nano banana pro 一次生成多图的小技巧",
    "date": "2026-01-15",
    "type": "图文",
    "impressions": 49717,
    "views": 7881,
    "ctr": 0.157,
    "likes": 371,
    "comments": 44,
    "saves": 602,
    "fans": 31,
    "shares": 154,
    "save_rate": 0.514,
    "quality_index": 1.51,
    "score": 11
  },
  {
    "title": "我的 2026 开年关键词：创造",
    "date": "2026-01-14",
    "type": "图文",
    "impressions": 920,
    "views": 114,
    "ctr": 0.13,
    "likes": 3,
    "comments": 0,
    "saves": 0,
    "fans": 2,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "让 AI 给我做了个播客自动生成发布工具",
    "date": "2026-01-12",
    "type": "图文",
    "impressions": 466,
    "views": 17,
    "ctr": 0.036,
    "likes": 0,
    "comments": 1,
    "saves": 1,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.5,
    "quality_index": 2.5,
    "score": 12
  },
  {
    "title": "2分钟讲清楚上下文图谱",
    "date": "2026-01-08",
    "type": "视频",
    "impressions": 837,
    "views": 125,
    "ctr": 0.041,
    "likes": 2,
    "comments": 0,
    "saves": 1,
    "fans": 1,
    "shares": 0,
    "save_rate": 0.333,
    "quality_index": 1.0,
    "score": 6
  },
  {
    "title": "马斯克：2026 年将出现通用人工智能",
    "date": "2026-01-07",
    "type": "图文",
    "impressions": 3103,
    "views": 313,
    "ctr": 0.092,
    "likes": 7,
    "comments": 0,
    "saves": 0,
    "fans": 3,
    "shares": 2,
    "save_rate": 0.0,
    "quality_index": 1.67,
    "score": 0
  },
  {
    "title": "2026 AI 创业 20 条猜想",
    "date": "2026-01-05",
    "type": "视频",
    "impressions": 638,
    "views": 144,
    "ctr": 0.027,
    "likes": 0,
    "comments": 0,
    "saves": 0,
    "fans": 1,
    "shares": 1,
    "save_rate": 0.0,
    "quality_index": 4.0,
    "score": 2
  },
  {
    "title": "DeepSeek的mHC可能会捅穿大模型天花板",
    "date": "2026-01-03",
    "type": "视频",
    "impressions": 2769,
    "views": 384,
    "ctr": 0.07,
    "likes": 12,
    "comments": 0,
    "saves": 9,
    "fans": 5,
    "shares": 2,
    "save_rate": 0.391,
    "quality_index": 1.26,
    "score": 7
  },
  {
    "title": "2026，与好奇心为伴",
    "date": "2026-01-02",
    "type": "视频",
    "impressions": 629,
    "views": 124,
    "ctr": 0.01,
    "likes": 0,
    "comments": 0,
    "saves": 0,
    "fans": 1,
    "shares": 0,
    "save_rate": 0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "索菲娅：数字生命的诞生",
    "date": "2026-01-01",
    "type": "视频",
    "impressions": 1368,
    "views": 265,
    "ctr": 0.056,
    "likes": 4,
    "comments": 0,
    "saves": 7,
    "fans": 0,
    "shares": 3,
    "save_rate": 0.5,
    "quality_index": 1.64,
    "score": 8
  },
  {
    "title": "Manus 的奇幻之旅",
    "date": "2025-12-30",
    "type": "视频",
    "impressions": 99,
    "views": 2,
    "ctr": 0.02,
    "likes": 0,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "一个普通人的 2025 AI 生存指南",
    "date": "2025-12-29",
    "type": "视频",
    "impressions": 643,
    "views": 144,
    "ctr": 0.043,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 1,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "Google这一年的AI跃迁不仅仅是Gemini 3",
    "date": "2025-12-21",
    "type": "图文",
    "impressions": 842,
    "views": 64,
    "ctr": 0.074,
    "likes": 2,
    "comments": 1,
    "saves": 1,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.2,
    "quality_index": 2.2,
    "score": 8
  },
  {
    "title": "Karpathy 的 2025年LLM回顾：六大范式转移",
    "date": "2025-12-20",
    "type": "图文",
    "impressions": 1701,
    "views": 155,
    "ctr": 0.093,
    "likes": 6,
    "comments": 0,
    "saves": 9,
    "fans": 0,
    "shares": 2,
    "save_rate": 0.529,
    "quality_index": 1.35,
    "score": 7
  },
  {
    "title": "ChatGPT 记忆秘密曝光：四层机制首次解密！",
    "date": "2025-12-18",
    "type": "图文",
    "impressions": 865,
    "views": 48,
    "ctr": 0.057,
    "likes": 4,
    "comments": 0,
    "saves": 4,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.444,
    "quality_index": 1.33,
    "score": 7
  },
  {
    "title": "这个开源工具让我彻底实现了PPT自由",
    "date": "2025-12-17",
    "type": "图文",
    "impressions": 4183,
    "views": 662,
    "ctr": 0.156,
    "likes": 13,
    "comments": 2,
    "saves": 23,
    "fans": 0,
    "shares": 6,
    "save_rate": 0.523,
    "quality_index": 1.55,
    "score": 11
  },
  {
    "title": "Banana Pro 模型的超强玩法",
    "date": "2025-12-10",
    "type": "图文",
    "impressions": 72,
    "views": 5,
    "ctr": 0.069,
    "likes": 0,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "Deepmind CEO 关于AI 的最新预测",
    "date": "2025-12-07",
    "type": "图文",
    "impressions": 2131,
    "views": 150,
    "ctr": 0.071,
    "likes": 6,
    "comments": 0,
    "saves": 7,
    "fans": 1,
    "shares": 0,
    "save_rate": 0.538,
    "quality_index": 1.0,
    "score": 7
  },
  {
    "title": "企业级 RAG 技术的应用与挑战",
    "date": "2025-12-06",
    "type": "图文",
    "impressions": 506,
    "views": 16,
    "ctr": 0.032,
    "likes": 2,
    "comments": 0,
    "saves": 2,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.4,
    "quality_index": 1.6,
    "score": 8
  },
  {
    "title": "世界模型：AGI的关键拼图",
    "date": "2025-12-01",
    "type": "视频",
    "impressions": 492,
    "views": 97,
    "ctr": 0.036,
    "likes": 2,
    "comments": 0,
    "saves": 1,
    "fans": 1,
    "shares": 1,
    "save_rate": 0.25,
    "quality_index": 1.75,
    "score": 5
  },
  {
    "title": "上下文工程讲解【湘北版】",
    "date": "2025-11-29",
    "type": "视频",
    "impressions": 565,
    "views": 69,
    "ctr": 0.051,
    "likes": 0,
    "comments": 0,
    "saves": 1,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.5,
    "quality_index": 2.5,
    "score": 9
  },
  {
    "title": "五分钟把技术论文变漫画！哆啦A梦亲自教学",
    "date": "2025-11-25",
    "type": "图文",
    "impressions": 70,
    "views": 2,
    "ctr": 0.029,
    "likes": 0,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "用 NotebookLM做动漫式学习材料太合适了！",
    "date": "2025-11-22",
    "type": "图文",
    "impressions": 1202,
    "views": 129,
    "ctr": 0.108,
    "likes": 3,
    "comments": 0,
    "saves": 4,
    "fans": 1,
    "shares": 2,
    "save_rate": 0.444,
    "quality_index": 1.67,
    "score": 8
  },
  {
    "title": "Google的AI智能体5日速成课程完整版出炉",
    "date": "2025-11-17",
    "type": "图文",
    "impressions": 3547,
    "views": 372,
    "ctr": 0.104,
    "likes": 39,
    "comments": 0,
    "saves": 41,
    "fans": 2,
    "shares": 12,
    "save_rate": 0.446,
    "quality_index": 1.39,
    "score": 7
  },
  {
    "title": "Google 最新 Agent 白皮书真香😍",
    "date": "2025-11-11",
    "type": "图文",
    "impressions": 1111,
    "views": 121,
    "ctr": 0.107,
    "likes": 10,
    "comments": 0,
    "saves": 11,
    "fans": 0,
    "shares": 4,
    "save_rate": 0.44,
    "quality_index": 1.48,
    "score": 8
  },
  {
    "title": "这个双十一花最值的一笔钱",
    "date": "2025-11-10",
    "type": "图文",
    "impressions": 711,
    "views": 89,
    "ctr": 0.122,
    "likes": 3,
    "comments": 0,
    "saves": 2,
    "fans": 0,
    "shares": 1,
    "save_rate": 0.333,
    "quality_index": 1.5,
    "score": 7
  },
  {
    "title": "被疯狂刷屏的DeepSeek-OCR模型为啥这么火?",
    "date": "2025-10-21",
    "type": "图文",
    "impressions": 776,
    "views": 54,
    "ctr": 0.061,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": 0,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "刚刚！Karpathy回应争议：AGI与人机协作未来",
    "date": "2025-10-19",
    "type": "图文",
    "impressions": 1804,
    "views": 227,
    "ctr": 0.124,
    "likes": 10,
    "comments": 0,
    "saves": 13,
    "fans": 1,
    "shares": 5,
    "save_rate": 0.464,
    "quality_index": 1.54,
    "score": 8
  }
];

var LIANGKEBAN_META = {
  "nickname": "两克伴",
  "followers": 209,
  "bio": "",
  "location": "深圳",
  "notes_count": 58,
  "total_impressions": 188306,
  "total_likes": 775,
  "total_saves": 1116,
  "total_comments": 61,
  "total_fans": 73,
  "total_shares": 316,
  "total_likes_and_saves": 1891,
  "total_engagement": 2268,
  "avg_save_rate": 0.286,
  "avg_quality_index": 1.53,
  "avg_comment_ratio": 0.035,
  "avg_score": 7,
  "analysis": "该账号内容以高收藏率和高互动质量为特点，TOP5笔记均呈现收藏率显著高于平均水平的趋势，收藏率集中在38.8%-66.5%区间，反映出用户对实用、高效类内容有强烈需求。从互动结构看，收藏型互动占比最高（平均28.6%），评论型互动占比最低（平均3.5%），分享型互动居中，整体呈现“收藏主导、评论辅助”的互动特点，内容实用性和价值感是吸引用户收藏的核心因素。\n\n建议：1.强化“技能教程+实操方法”的内容方向，如“AI工具实操指南”系列，提升内容可操作性；2.增加互动引导，如在笔记结尾设置“你的使用心得”等开放性问题，促进评论互动，平衡收藏与评论比例。",
  "profile_tags": {
    "follower_tier": "素人",
    "primary_vertical": "AI工具",
    "secondary_vertical": null,
    "content_style": "干货教程",
    "content_consistency": "高",
    "engagement_quality": "中",
    "content_format": "图文为主",
    "commercial_stage": "起步期",
    "tagged_at": "2026-04-13"
  }
};
