var LIANGKEBAN_DATA = [
  {
    "title": "nano banana pro 一次生成多图的小技巧",
    "date": "2026-01-15",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 373,
    "comments": 44,
    "saves": 610,
    "fans": null,
    "shares": 154,
    "save_rate": 0.517,
    "quality_index": 1.5,
    "score": 67
  },
  {
    "title": "OpenClaw 和 Hermes 怎么选🤔",
    "date": "2026-04-12",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 5,
    "comments": 0,
    "saves": 13,
    "fans": null,
    "shares": 2,
    "save_rate": 0.65,
    "quality_index": 1.3,
    "score": 56
  },
  {
    "title": "💰这家神仙公司如何做到99.5%员工都用AI？",
    "date": "2026-04-11",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "我把Karpathy个人知识管理方法做成了skill",
    "date": "2026-04-06",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 63,
    "comments": 6,
    "saves": 165,
    "fans": null,
    "shares": 33,
    "save_rate": 0.618,
    "quality_index": 1.44,
    "score": 63
  },
  {
    "title": "🚀Gemma 4 的 8 个版本怎么选？一文看懂！",
    "date": "2026-04-03",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 18,
    "comments": 0,
    "saves": 30,
    "fans": null,
    "shares": 5,
    "save_rate": 0.5660000000000001,
    "quality_index": 1.28,
    "score": 55
  },
  {
    "title": "AI 重塑组织：Block 的\"智能体公司\"实验",
    "date": "2026-04-01",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 6,
    "comments": 2,
    "saves": 16,
    "fans": null,
    "shares": 1,
    "save_rate": 0.64,
    "quality_index": 1.36,
    "score": 59
  },
  {
    "title": "axios被投毒！建议所有养🦞的朋友立即自检",
    "date": "2026-03-31",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 5,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 3,
    "save_rate": 0.2,
    "quality_index": 1.9,
    "score": 59
  },
  {
    "title": "造好 Harness，Agent 会完成剩下的",
    "date": "2026-03-27",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "苹果秘密协议曝光！把Gemini放到iPhone 里？",
    "date": "2026-03-27",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "林俊暘离开阿里首度发声：AI 下一个方向是它",
    "date": "2026-03-26",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "🍌banana pro 一次生成多张黑白票据图技巧",
    "date": "2026-03-26",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 1,
    "save_rate": 0.0,
    "quality_index": 2.0,
    "score": 40
  },
  {
    "title": "🦞微信里也可以实现养虾自由啦！含详细教程",
    "date": "2026-03-22",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "🔥 国产AI反向输出美国科技圈",
    "date": "2026-03-21",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "Skill实战手册：装了100个不如用好1个",
    "date": "2026-03-20",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1,
    "comments": 2,
    "saves": 2,
    "fans": null,
    "shares": 0,
    "save_rate": 0.4,
    "quality_index": 2.2,
    "score": 72
  },
  {
    "title": "🚀 英伟达GTC2026完全看懂这篇就够了",
    "date": "2026-03-17",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 1,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 4,
    "save_rate": 0.28600000000000003,
    "quality_index": 2.71,
    "score": 75
  },
  {
    "title": "想知道龙虾有多了解你，问这三个问题就够了",
    "date": "2026-03-13",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "Google 发布一个王炸模型，直接颠覆RAG！🔥",
    "date": "2026-03-11",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 3,
    "fans": null,
    "shares": 1,
    "save_rate": 0.5,
    "quality_index": 1.5,
    "score": 65
  },
  {
    "title": "🦞别再把龙虾当微信用了",
    "date": "2026-03-11",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  },
  {
    "title": "4万个AI Skills，95%都是垃圾？",
    "date": "2026-03-10",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 1,
    "save_rate": 0.0,
    "quality_index": 2.0,
    "score": 40
  },
  {
    "title": "🔥 你的AI员工来了！",
    "date": "2026-03-07",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 1,
    "save_rate": 0.0,
    "quality_index": 2.0,
    "score": 40
  }
];

var LIANGKEBAN_META = {
  "nickname": "两克伴",
  "xhs_id": 195768272,
  "bio": "探寻智能商业的魅力",
  "location": "广东",
  "followers": 209,
  "following": 61,
  "notes_count": 81,
  "total_likes": 1310,
  "total_saves": 1988,
  "total_likes_and_saves": 3298,
  "total_engagement": 1595,
  "avg_save_rate": 0.21899999999999997,
  "avg_quality_index": 1.46,
  "avg_comment_ratio": 0.027000000000000003,
  "avg_score": 38,
  "analysis": "「两克伴」账号以深度技术教程类内容表现突出，TOP5笔记均围绕AI工具、方法或产品选型，收藏率高达50%-67%，印证了专业、实用干货是核心爆款特征。互动结构以收藏主导（平均21.9%），辅以少量高质量评论（平均2.7%），分享转化较弱。建议：1. 强化实操演示类内容，结合「 nano banana pro」的爆款模式，增加教程步骤图/视频提升收藏率；2. 挖掘粉丝痛点设计互动问答环节，如「OpenClaw和Hermes怎么选」的评论区互动，引导深度评论，提升互动质量指数。"
};
