var LIANGKEBAN_DATA = [
  {
    "title": "我把Karpathy个人知识管理方法做成了skill",
    "date": "2026-04-06",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 102,
    "comments": 10,
    "saves": 267,
    "fans": null,
    "shares": 51,
    "save_rate": 0.621,
    "quality_index": 1.43,
    "score": 63
  },
  {
    "title": "nano banana pro 一次生成多图的小技巧",
    "date": "2026-01-15",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 391,
    "comments": 44,
    "saves": 652,
    "fans": null,
    "shares": 161,
    "save_rate": 0.522,
    "quality_index": 1.49,
    "score": 66
  },
  {
    "title": "未来 3 年最值得普通人入局的创业机会",
    "date": "2026-05-17",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 6,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 1,
    "save_rate": 0.222,
    "quality_index": 1.33,
    "score": 50
  },
  {
    "title": "注意力，才是这个时代最贵的资源",
    "date": "2026-05-16",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 7,
    "comments": 0,
    "saves": 8,
    "fans": null,
    "shares": 1,
    "save_rate": 0.5,
    "quality_index": 1.19,
    "score": 50
  },
  {
    "title": "为什么硅谷这个岗位能年薪 300 万？",
    "date": "2026-05-15",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 7,
    "comments": 0,
    "saves": 1,
    "fans": null,
    "shares": 0,
    "save_rate": 0.125,
    "quality_index": 1.0,
    "score": 22
  },
  {
    "title": "世界不再奖励“拼命的人”",
    "date": "2026-05-14",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 1,
    "fans": null,
    "shares": 0,
    "save_rate": 0.33299999999999996,
    "quality_index": 1.0,
    "score": 40
  },
  {
    "title": "成年人正在批量NPC化",
    "date": "2026-05-13",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 13,
    "comments": 4,
    "saves": 22,
    "fans": null,
    "shares": 4,
    "save_rate": 0.512,
    "quality_index": 1.56,
    "score": 70
  },
  {
    "title": "Claude Code 新功能：AI 多任务终于不乱了",
    "date": "2026-05-12",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 0,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 0
  },
  {
    "title": "智能体时代全面开启",
    "date": "2026-05-09",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 11,
    "comments": 0,
    "saves": 6,
    "fans": null,
    "shares": 1,
    "save_rate": 0.33299999999999996,
    "quality_index": 1.17,
    "score": 49
  },
  {
    "title": "为什么说 AI 不会导致大失业",
    "date": "2026-05-07",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 3,
    "comments": 0,
    "saves": 1,
    "fans": null,
    "shares": 0,
    "save_rate": 0.25,
    "quality_index": 1.0,
    "score": 35
  },
  {
    "title": "微软最新报告：AI 正在重构整个组织体系",
    "date": "2026-05-06",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 5,
    "comments": 1,
    "saves": 7,
    "fans": null,
    "shares": 0,
    "save_rate": 0.5379999999999999,
    "quality_index": 1.23,
    "score": 52
  },
  {
    "title": "一张图讲清楚Agent Harness 是什么",
    "date": "2026-05-06",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 3,
    "comments": 0,
    "saves": 7,
    "fans": null,
    "shares": 1,
    "save_rate": 0.636,
    "quality_index": 1.27,
    "score": 54
  },
  {
    "title": "公司大脑：为什么多数公司有数据却没记忆",
    "date": "2026-05-05",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 23,
    "comments": 1,
    "saves": 41,
    "fans": null,
    "shares": 10,
    "save_rate": 0.547,
    "quality_index": 1.44,
    "score": 63
  },
  {
    "title": "AI的未来不是更强，而是更多。",
    "date": "2026-05-05",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 4,
    "comments": 0,
    "saves": 4,
    "fans": null,
    "shares": 0,
    "save_rate": 0.5,
    "quality_index": 1.0,
    "score": 40
  },
  {
    "title": "AI不是变强，而是变“结构”",
    "date": "2026-05-04",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 7,
    "comments": 0,
    "saves": 6,
    "fans": null,
    "shares": 1,
    "save_rate": 0.429,
    "quality_index": 1.21,
    "score": 51
  },
  {
    "title": "软件，正在失去价值",
    "date": "2026-05-03",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 5,
    "comments": 1,
    "saves": 3,
    "fans": null,
    "shares": 2,
    "save_rate": 0.273,
    "quality_index": 1.82,
    "score": 77
  },
  {
    "title": "howto",
    "date": "3",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 0,
    "comments": 51,
    "saves": 36,
    "fans": null,
    "shares": 3,
    "save_rate": 0.4,
    "quality_index": 2.8,
    "score": 82
  },
  {
    "title": "💡AI原生公司正在重写规则",
    "date": "2026-04-28",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 3,
    "comments": 0,
    "saves": 1,
    "fans": null,
    "shares": 1,
    "save_rate": 0.2,
    "quality_index": 1.6,
    "score": 56
  },
  {
    "title": "💡Snap CEO揭秘：AI时代唯一的出路是“分发”！",
    "date": "2026-04-27",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 3,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 1,
    "save_rate": 0.33299999999999996,
    "quality_index": 1.5,
    "score": 65
  },
  {
    "title": "🦞装上这个技能帮你打败99%的演唱会黄牛",
    "date": "2026-04-17",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 2,
    "comments": 0,
    "saves": 0,
    "fans": null,
    "shares": 0,
    "save_rate": 0.0,
    "quality_index": 1.0,
    "score": 9
  }
];

var LIANGKEBAN_META = {
  "nickname": "两克伴",
  "xhs_id": 195768272,
  "bio": "探寻智能商业的魅力",
  "location": "Guangdong",
  "followers": 250,
  "following": 64,
  "notes_count": 103,
  "total_likes": 1535,
  "total_saves": 2321,
  "total_likes_and_saves": 3856,
  "total_engagement": 2014,
  "avg_save_rate": 0.364,
  "avg_quality_index": 1.35,
  "avg_comment_ratio": 0.045,
  "avg_score": 49,
  "analysis": "「两克伴」账号的爆款内容呈现明显的技术与知识分享属性，特别是实操教程类笔记（如「nano banana pro」）收藏率高达52.2%，互动质量指数与综合评分均领先。互动结构以收藏型为主（平均36.4%），辅以高互动质量（平均1.35），但评论/互动比仅4.5%，可见用户偏好快速获取信息而非深度讨论。\n\n建议：1. 持续深化「技巧/教程」类内容，强化步骤可视化，提升收藏转化；2. 尝试在教程结尾设置开放性问题或投票，引导评论互动，平衡收藏与讨论比例。",
  "profile_tags": {
    "content_theme": {
      "primary_vertical": "AI工具",
      "sub_direction": "AI效率工具"
    },
    "content_style": {
      "audience_level": "进阶向",
      "sentence_pattern": "教程型",
      "tone": "干货严肃"
    },
    "seeding_traits": {
      "seeding_tendency": "纯干货",
      "suitable_ad_type": "工具软件类"
    },
    "engagement_traits": {
      "fan_activity": "高活跃",
      "content_burst": "爆款型",
      "seeding_efficiency": "均衡型"
    },
    "account_health": {
      "update_freq": "高频",
      "content_verticality": "高垂直",
      "engagement_authenticity": "正常"
    },
    "collab_fit": {
      "recommended_scenario": "产品教程",
      "brand_tone_match": "专业科技品牌"
    },
    "follower_tier": "素人",
    "content_format": "图文为主",
    "tagged_at": "2026-05-17"
  }
};
