var LUMOSEDUCATION_DATA = [
  {
    "title": "🇦🇺 澳大利亚悉尼｜顶级师资团队",
    "date": "2024-07-24",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 19,
    "comments": 31,
    "saves": 11,
    "fans": null,
    "shares": 7,
    "save_rate": 0.162,
    "quality_index": 2.68,
    "score": 76
  },
  {
    "title": "🎉12年级化学🧪年级第1，2，4！",
    "date": "2026-04-10",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 5,
    "comments": 0,
    "saves": 1,
    "fans": null,
    "shares": 0,
    "save_rate": 0.16699999999999998,
    "quality_index": 1.0,
    "score": 26
  },
  {
    "title": "🧪Y11 Chem化学NSW学校秋假｜高分小班招生",
    "date": "2026-04-08",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 4,
    "comments": 0,
    "saves": 1,
    "fans": null,
    "shares": 2,
    "save_rate": 0.14300000000000002,
    "quality_index": 1.86,
    "score": 52
  },
  {
    "title": "🙌来小红书8周年啦！",
    "date": "2026-03-12",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 6,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 0,
    "save_rate": 0.25,
    "quality_index": 1.0,
    "score": 35
  },
  {
    "title": "来自我校一位英语班学生的评价",
    "date": "2026-03-02",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 6,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 0,
    "save_rate": 0.25,
    "quality_index": 1.0,
    "score": 35
  },
  {
    "title": "Chatswood这家补习班，直接杀出个年级第一🏅",
    "date": "2026-03-02",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 7,
    "comments": 0,
    "saves": 5,
    "fans": null,
    "shares": 2,
    "save_rate": 0.35700000000000004,
    "quality_index": 1.43,
    "score": 63
  },
  {
    "title": "HSC英语想冲高分？官方Marker来了",
    "date": "2026-02-06",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 9,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 0,
    "save_rate": 0.182,
    "quality_index": 1.0,
    "score": 28
  },
  {
    "title": "通往剑桥大学的路，从小开始",
    "date": "2026-01-30",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 7,
    "comments": 0,
    "saves": 3,
    "fans": null,
    "shares": 1,
    "save_rate": 0.273,
    "quality_index": 1.27,
    "score": 52
  },
  {
    "title": "教学被肯定",
    "date": "2026-01-25",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 8,
    "comments": 0,
    "saves": 2,
    "fans": null,
    "shares": 0,
    "save_rate": 0.2,
    "quality_index": 1.0,
    "score": 30
  },
  {
    "title": "10年级英语｜升班成功🏆达芬奇｜实力见证成长",
    "date": "2025-12-22",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 7,
    "comments": 0,
    "saves": 4,
    "fans": null,
    "shares": 0,
    "save_rate": 0.364,
    "quality_index": 1.0,
    "score": 40
  },
  {
    "title": "从Year 5陪跑到ATAR 99.70：看着他长大🎓✨",
    "date": "2025-12-20",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 9,
    "comments": 1,
    "saves": 3,
    "fans": null,
    "shares": 1,
    "save_rate": 0.214,
    "quality_index": 1.43,
    "score": 54
  },
  {
    "title": "🏆 Atar 97.65｜HSC英語數學高分选手🔥",
    "date": "2025-12-20",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 8,
    "comments": 0,
    "saves": 1,
    "fans": null,
    "shares": 1,
    "save_rate": 0.1,
    "quality_index": 1.3,
    "score": 36
  },
  {
    "title": "HSC化学｜93%成绩，ATAR 97.8 🧪",
    "date": "2025-12-19",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 9,
    "comments": 0,
    "saves": 3,
    "fans": null,
    "shares": 0,
    "save_rate": 0.25,
    "quality_index": 1.0,
    "score": 35
  },
  {
    "title": "AEAS7-9年级74分，澳大利亚悉尼私立学校入学",
    "date": "2025-12-19",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 7,
    "comments": 2,
    "saves": 2,
    "fans": null,
    "shares": 1,
    "save_rate": 0.16699999999999998,
    "quality_index": 1.75,
    "score": 65
  },
  {
    "title": "🎓 Year 8 Science｜年级第一",
    "date": "2025-12-17",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 9,
    "comments": 1,
    "saves": 2,
    "fans": null,
    "shares": 5,
    "save_rate": 0.11800000000000001,
    "quality_index": 2.06,
    "score": 60
  },
  {
    "title": "2026 7年级NAPLAN备考班🔥",
    "date": "2025-12-05",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 8,
    "comments": 4,
    "saves": 5,
    "fans": null,
    "shares": 0,
    "save_rate": 0.294,
    "quality_index": 1.71,
    "score": 66
  },
  {
    "title": "2026 NAPLAN备考班｜5年级课程开启报名",
    "date": "2025-12-05",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 10,
    "comments": 0,
    "saves": 3,
    "fans": null,
    "shares": 0,
    "save_rate": 0.231,
    "quality_index": 1.0,
    "score": 33
  },
  {
    "title": "🎉 2025 年考｜8年级 English 100%",
    "date": "2025-11-14",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 9,
    "comments": 0,
    "saves": 5,
    "fans": null,
    "shares": 2,
    "save_rate": 0.312,
    "quality_index": 1.38,
    "score": 60
  },
  {
    "title": "🎉 2025 年考｜9年级科学95%",
    "date": "2025-11-13",
    "type": null,
    "impressions": null,
    "views": null,
    "ctr": null,
    "likes": 10,
    "comments": 3,
    "saves": 3,
    "fans": null,
    "shares": 0,
    "save_rate": 0.188,
    "quality_index": 1.56,
    "score": 54
  }
];

var LUMOSEDUCATION_META = {
  "nickname": "LUMOS EDUCATION",
  "xhs_id": 959546352,
  "bio": "",
  "location": "澳大利亚",
  "followers": 282,
  "following": 49,
  "notes_count": 74,
  "total_likes": 1685,
  "total_saves": 357,
  "total_likes_and_saves": 2042,
  "total_engagement": 349,
  "avg_save_rate": 0.21899999999999997,
  "avg_quality_index": 1.45,
  "avg_comment_ratio": 0.08199999999999999,
  "avg_score": 48,
  "analysis": "LUMOS EDUCATION账号的爆款内容集中于展示「师资团队」（悉尼顶级师资团队笔记出现2次），这类内容平均互动质量指数（2.68）和综合评分（76）远超其他笔记，表明高价值师资介绍能有效吸引粉丝。互动结构上，收藏率（21.9%）高于评论率（8.2%），但TOP笔记均以评论量见长（平均8.2%），显示内容兼具实用性（收藏）和话题性（评论）。\n\n建议：1）持续深化师资团队内容，突出专业背景与教学成果，结合「地域+师资」标签强化搜索曝光；2）增加互动引导，如发起「你希望了解哪个国家教育体系」投票，提升评论率，优化互动结构平衡。",
  "profile_tags": {
    "content_theme": {
      "primary_vertical": "教育",
      "sub_direction": "K12"
    },
    "content_style": {
      "audience_level": "进阶向",
      "sentence_pattern": "清单型",
      "tone": "干货严肃"
    },
    "seeding_traits": {
      "seeding_tendency": "中性分享",
      "suitable_ad_type": "课程教育"
    },
    "engagement_traits": {
      "fan_activity": "中活跃",
      "content_burst": "波动型",
      "seeding_efficiency": "均衡型"
    },
    "account_health": {
      "update_freq": "中频",
      "content_verticality": "高垂直",
      "engagement_authenticity": "正常"
    },
    "collab_fit": {
      "recommended_scenario": "产品教程",
      "brand_tone_match": "教育知识类"
    },
    "follower_tier": "素人",
    "content_format": "图文为主",
    "tagged_at": "2026-04-20"
  }
};
